### PR TITLE
Add  file content read for Python 3 (keep compat with Python 2.7)

### PR DESCRIPTION
**Pull request by regisf**
Allow Python 3 program to upload files in JSON format. Otherwise a `is not JSON serializable` error occure.

### CODE REVIEW

**Comment by demoore** [comment]
Thanks @regisf ! Someone at Sendwithus will look at this in the next couple of weeks. 😸

**Comment by regisf** [comment]
All tests pass, but there was a bug remaining in some case with some binary file. Just fix the problem. Sorry for the noise.

**Comment by demoore** [comment]
Hey @regisf functionally this looks fine, but would you be able to use [six](http://pythonhosted.org/six/) to check which version of python is being run?

**Comment by demoore** [comment]
Thanks @regisf !

**Pull request merged**
